# use a fixed random seed to guarantee that when you run the code twice you will get the same outcome
manual_seed: 0
# model configuration
model:
  # model class
  name: VaeUNet
  # number of input channels to the model
  in_channels: 4
  # number of output channels
  out_channels: 4
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: cbr
  # feature maps scale factor
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
# trainer configuration
trainer:
  # path to the checkpoint directory
<<<<<<< HEAD
  checkpoint_dir: /home/server/github/pytorch-3dunet/checkpoints/vae_model_kaiming_swa_DataAug_boudaryloss/
=======
  checkpoint_dir: /home/server/github/pytorch-3dunet/checkpoints/vae_model_kaiming_swa_DataAug/
>>>>>>> temp
  # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  resume: null
  # how many iterations between validations
  validate_after_iters: 50
  # how many iterations between tensorboard logging
  log_after_iters: 20
  # max number of epochs
  epochs: 100
  # max number of iterations
  iters: 100000
  # model with higher eval score is considered better
  eval_score_higher_is_better: True
# optimizer configuration
optimizer:
  #mode
  mode: SWA
  # initial learning rate
  learning_rate: 0.00001
  # weight decay
  weight_decay: 0.003
# loss function configuration
loss:
  # loss function to be used during training
  name: VaeLoss
  # A manual rescaling weight given to each class.
  loss_weight: null
  # a target value that is ignored and does not contribute to the input gradient
  ignore_index: null
# evaluation metric configuration
eval_metric:
  name: DiceCoefficient
  # a target label that is ignored during metric evaluation
  ignore_index: null
lr_scheduler:
  name: ExponentialLR
  #milestones: [10, 30, 60]
<<<<<<< HEAD
  gamma: 0.99
=======
  gamma: 0.2
>>>>>>> temp
# data loaders configuration
loaders:
  # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
  train_patch: [32, 64, 64]
  # train stride between patches
  train_stride: [8, 16, 16]
  # validation patch (can be bigger than train patch since there is no backprop)
  val_patch: [32, 64, 64]
  # validation stride (validation patches doesn't need to overlap)
  val_stride: [32, 64, 64]
  # path to the raw data within the H5
  raw_internal_path: raw
  # path to the the label data withtin the H5
  label_internal_path: label
  # paths to the training datasets
  train_path:
    - 'resources/random_label3D.h5'
  # paths to the validation datasets
  val_path:
    - 'resources/random_label3D.h5'
  dataset_path:
    - '/home/server/data'
  # how many subprocesses to use for data loading
  num_workers: 8
  # data transformations/augmentations
  transformer:
    train:
      raw:
        - name: Normalize
        - name: RandomFlip
        - name: RandomRotate
          # rotate only in ZY only
          axes: [[2, 1]]
          angle_spectrum: 15
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
        - name: RandomContrast
        - name: ToTensor
          expand_dims: true
      label:
        - name: RandomFlip
        - name: RandomRotate
          # rotate only in ZY only
          axes: [[2, 1]]
          angle_spectrum: 15
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
        - name: ToTensor
          expand_dims: true
          dtype: 'long'
    test:
      raw:
        - name: Normalize
        - name: ToTensor
          expand_dims: true
      label:
        - name: ToTensor
          expand_dims: true
          dtype: 'long'
